name: Bryan W. Weber
markdown: kramdown
highlighter: rouge
kramdown:
    auto_ids: false
lsi: false
permalink: /writing/:categories/:year/:month/:day/:title
baseurl: 
exclude: [.gitignore, .git]
excerpt_separator : <!--more-->
encoding: UTF-8
